#pragma once

#ifdef __cplusplus
extern "C" {
#endif

typedef enum TlalpowaCommand {
    TLALPOWA_COMMAND_DEFAULT = 0,
    TLALPOWA_COMMAND_SELFTEST,
    TLALPOWA_COMMAND_ATMOSPHERE,
    TLALPOWA_COMMAND_ATMOSPHERE_WEB,
    TLALPOWA_COMMAND_EPI_WEB,
    TLALPOWA_COMMAND_EXTERNAL_SMOKE,
    TLALPOWA_COMMAND_SATELLITE_WEB,
    TLALPOWA_COMMAND_EPI_AUDIT,
    TLALPOWA_COMMAND_IXIPTLAH_PURGE_EPI_FILE,
    TLALPOWA_COMMAND_LAUNCHER,
    TLALPOWA_COMMAND_GUI,
    TLALPOWA_COMMAND_APP,
    TLALPOWA_COMMAND_RUN,
    TLALPOWA_COMMAND_UNKNOWN
} TlalpowaCommand;

int tlalpowa_execute_command(TlalpowaCommand command, int argc, char** argv);

#ifdef __cplusplus
}
#endif
