<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="Miausoft Target PreImport">
    <TargetName>Organizador</TargetName>
  </PropertyGroup>
  <Import Project="$(MSBuildThisFileDirectory)Miausoft.Output.Root.props" />
  <PropertyGroup Label="Miausoft Target">
    <TargetName>Organizador</TargetName>
    <OutDir>$(MiausoftRootDir)</OutDir>
    <MiausoftFinalExe>$(MiausoftRootDir)$(TargetName)$(TargetExt)</MiausoftFinalExe>
    <TargetPath>$(MiausoftFinalExe)</TargetPath>
  </PropertyGroup>
  <ItemDefinitionGroup Label="Miausoft Heavy Resources">
    <ClCompile>
      <AdditionalOptions>/bigobj /MP %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
    <Link>
      <OutputFile>$(MiausoftFinalExe)</OutputFile>
      <LargeAddressAware>true</LargeAddressAware>
      <AdditionalOptions>/LARGEADDRESSAWARE /STACK:1073741824,16777216 /HEAP:2147483648,33554432 %(AdditionalOptions)</AdditionalOptions>
    </Link>
  </ItemDefinitionGroup>
</Project>
